[package]
name = "testcrate"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
rand_xoshiro = { version = "0.6", default-features = false }
starlight = { path = "../starlight", features = ["debug"] }
