[workspace]
resolver = "2"
members = [
    "starlight",
    "testcrate",
]

[patch.crates-io]
triple_arena = { path = "../triple_arena/triple_arena" }
triple_arena_render = { path = "../triple_arena/triple_arena_render", optional = true }
